### ISSUE TITLE
job Crawl: key errors

### ISSUE THREAD

**Issue by luckydogxf** [opensanctions/opensanctions#224]
```
2022-08-04 21:39:38 [info     ] Crawl 'Samoa'                  [interpol_red_notices] code=WS dataset=interpol_red_notices
2022-08-04 21:39:38 [info     ] Crawl 'Yemen'                  [interpol_red_notices] code=YE dataset=interpol_red_notices
2022-08-04 21:39:39 [info     ] Crawl 'South Africa'           [interpol_red_notices] code=ZA dataset=interpol_red_notices
2022-08-04 21:39:39 [info     ] Crawl 'Zambia'                 [interpol_red_notices] code=ZM dataset=interpol_red_notices
2022-08-04 21:39:40 [info     ] Crawl 'Zimbabwe'               [interpol_red_notices] code=ZW dataset=interpol_red_notices
2022-08-04 21:39:45 [info     ] Crawl completed                [everypolitician] dataset=everypolitician entities=73795 targets=73795
2022-08-04 21:40:24 [info     ] Crawl completed                [interpol_red_notices] dataset=interpol_red_notices entities=6850 targets=6850
2022-08-04 21:43:06 [info     ] Crawl completed                [us_ofac_sdn] dataset=us_ofac_sdn entities=33792 targets=9108
Traceback (most recent call last):
  File "/usr/local/bin/opensanctions", line 33, in <module>
    sys.exit(load_entry_point('opensanctions', 'console_scripts', 'opensanctions')())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opensanctions/opensanctions/cli.py", line 58, in run
    run_pipeline(dataset, threads=threads)
  File "/opensanctions/opensanctions/processing.py", line 32, in run_pipeline
    _compute_futures(futures)
  File "/opensanctions/opensanctions/processing.py", line 16, in _compute_futures
    future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opensanctions/opensanctions/core/context.py", line 244, in crawl
    self.dataset.method(self)
  File "/opensanctions/opensanctions/crawlers/ru_acf_bribetakers.py", line 35, in crawl
    crawl_row(context, row)
  File "/opensanctions/opensanctions/crawlers/ru_acf_bribetakers.py", line 16, in crawl_row
    name_en = row.pop("Name eng")
KeyError: 'Name eng'
```
I googled and found this link https://acf.international/acf-media/War_Arrangers_Security_council_members_TRpZp4n.pdf
There is such attribute 'Name eng'.

I'm new to this project, anyway to fix this ?

**Comment by luckydogxf** [comment]
And there is one more issue
```
2022-08-04 20:52:40 [info     ] Crawl 'Palestine, State of'    [interpol_red_notices] code=PS dataset=interpol_red_notices
2022-08-04 20:52:40 [info     ] Crawl 'Portugal'               [interpol_red_notices] code=PT dataset=interpol_red_notices
2022-08-04 20:52:41 [info     ] Crawl 'Palau'                  [interpol_red_notices] code=PW dataset=interpol_red_notices
2022-08-04 20:52:41 [info     ] Crawl 'Paraguay'               [interpol_red_notices] code=PY dataset=interpol_red_notices
2022-08-04 20:52:44 [info     ] Crawl 'Qatar'                  [interpol_red_notices] code=QA dataset=interpol_red_notices
2022-08-04 20:52:45 [info     ] Crawl 'Romania'                [interpol_red_notices] code=RO dataset=interpol_red_notices
2022-08-04 20:52:47 [info     ] Crawl 'Serbia'                 [interpol_red_notices] code=RS dataset=interpol_red_notices
2022-08-04 20:52:47 [info     ] Crawl 'Russia'                 [interpol_red_notices] code=RU dataset=interpol_red_notices
2022-08-04 20:52:53 [info     ] Crawl completed                [eu_fsf] dataset=eu_fsf entities=6390 targets=2445
2022-08-04 20:52:53 [info     ] Begin crawl                    [gb_coh_disqualified] dataset=gb_coh_disqualified
2022-08-04 20:53:36 [info     ] Rate limit exceeded, aborting. [gb_coh_disqualified] dataset=gb_coh_disqualified
2022-08-04 20:54:14 [info     ] Crawl completed                [gb_coh_disqualified] dataset=gb_coh_disqualified entities=5230 targets=1000
2022-08-04 20:54:14 [info     ] Begin crawl                    [us_occ_enfact] dataset=us_occ_enfact

2022-08-04 20:54:14 [info     ] Begin crawl                    [us_occ_enfact] dataset=us_occ_enfact
2022-08-04 20:54:14 [info     ] Fetching resource              [us_occ_enfact] dataset=us_occ_enfact path=/opensanctions/data/datasets/us_occ_enfact/source.json url=https://apps.occ.gov/EASearch/Search/ExportToJSON?Search=&StartDateMinimum=&StartDateMaximum=&TerminationDateMinimum=&TerminationDateMaximum=&ShowIndividualActionsOnly=false&ShowInstitutionActionsOnly=false&ShowTerminatedActionsOnly=false&ShowActiveOnly=false&Category=&Sort=BankName&AutoCompleteSelection=&CurrentPageIndex=0&ItemsPerPage=10&view=Table&IsAdvanced=true
2022-08-04 20:54:25 [error    ] Crawl failed                   [us_occ_enfact] dataset=us_occ_enfact
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 996, in _prepare_proxy
    conn.connect()
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.10/ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1070, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='apps.occ.gov', port=443): Max retries exceeded with url: /EASearch/Search/ExportToJSON?Search=&StartDateMinimum=&StartDateMaximum=&TerminationDateMinimum=&TerminationDateMaximum=&ShowIndividualActionsOnly=false&ShowInstitutionActionsOnly=false&ShowTerminatedActionsOnly=false&ShowActiveOnly=false&Category=&Sort=BankName&AutoCompleteSelection=&CurrentPageIndex=0&ItemsPerPage=10&view=Table&IsAdvanced=true (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:997)')))

```
It's possibly due to either networking connection issue or the target does not allow us to acccess.
`curl https://apps.occ.gov/ -I `  hangs forever.

Can we skip such kind of exception? so that remaining jobs won't be  aborted.

**Comment by pudo** [comment]
Hey @luckydogxf, thanks for submitting these issues. Let me take them on separately:

a) Regarding the ACF list. The relevant file is https://acf.international/acf-media/Contributors_to_the_war_csv_nDCHrhV.csv, which does have the `Name eng` column. More broadly, I worry that you may not have cleared the local cache before re-running the pipeline. Basically: every day, before running the pipeline, you should clear out the `$OPENSANCTIONS_DATA_PATH/datasets` folder (usually: `data/datasets`). Otherwise cached versions of the data are used - in the case of the ACF list, that's an old version with different column names. 

b) Regarding the OCC site, that's weird. Are you running from a funky location?

Anyway, your report regarding the errors (and them aborting the pipeline) is not the first, and I'll make a new ticket to describe a proposed solution. 

p.s. Errors like the ACF thing show up in the different data sources every day. You can always see the errors from the last run on my infra here: https://www.opensanctions.org/issues/ - and if something is listed there, you don't need to open a ticket. I'm trying to fix these errors as quickly as possible, usually within 48hrs. Organisations that depend on the data can support this work by licensing the data: https://www.opensanctions.org/docs/commercial-faq/

**Comment by pudo** [comment]
See #225.

**Comment by luckydogxf** [comment]
Regarding the OCC site, that's weird. 
---> Probably this site denies our access becase we're not on the whitelist. 

Gotcha, thanks for you kind reply.
