### ISSUE TITLE
OPENSANCTIONS_RESOLVER_PATH issue - downloaded resolve.ijson

### ISSUE THREAD

**Issue by LandonStewart** [opensanctions/opensanctions#252]
Hello,

# Environment:
```
$ uname -a
Darwin Landons-iMac.local 20.6.0 Darwin Kernel Version 20.6.0: Thu Sep 29 20:15:11 PDT 2022; root:xnu-7195.141.42~1/RELEASE_X86_64 x86_64
$ docker -v
Docker version 20.10.21, build baeda1f
$ git pull
Already up to date.
```

# Problem:
I downloaded the file [resolve.ijson](https://github.com/opensanctions/opensanctions/blob/aeddc039bb581c3671791687603a1dd646de6c89/opensanctions/static/resolve.ijson) and put it in `data/`.  After setting the environment variable `OPENSANCTIONS_RESOLVER_PATH` the dedupe candidates do not build.  Fails while `Building index blocking pairs` with `UnboundLocalError: local variable 'idx' referenced before assignment`.

I don't know where to go from here.

# Output:
```
docker-compose run --rm app bash
root@work:/opensanctions# echo $OPENSANCTIONS_RESOLVER_PATH
/opensanctions/data/resolve.ijson
root@work:/opensanctions# opensanctions xref -l 50000 sanctions
2022-11-30 01:01:56 [info     ] Resolving canonical_id in statements... [opensanctions.core.statements] resolver=<Resolver('resolve.ijson', 185540)>
2022-11-30 01:02:12 [info     ] Xref running, auto merge threshold: 0.990000 [opensanctions.core.xref] 
2022-11-30 01:02:12 [info     ] Loading database cache...      [opensanctions.core.loader] scope=<Collection('sanctions')>
2022-11-30 01:02:12 [info     ] Begin xref: <CachedDatasetLoader(<Collection('sanctions')>)>, resolver: <Resolver('resolve.ijson', 185540)> [nomenklatura.xref] 
2022-11-30 01:02:12 [info     ] Building index from: <CachedDatasetLoader(<Collection('sanctions')>)>... [nomenklatura.index.index] 
2022-11-30 01:02:12 [info     ] Built index: <Index('sanctions', 0, 0)> [nomenklatura.index.index] 
2022-11-30 01:02:12 [info     ] Building index blocking pairs... [nomenklatura.index.index] 
Traceback (most recent call last):
  File "/usr/local/bin/opensanctions", line 33, in <module>
    sys.exit(load_entry_point('opensanctions', 'console_scripts', 'opensanctions')())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opensanctions/opensanctions/cli.py", line 99, in xref
    blocking_xref(dataset, limit=limit, auto_threshold=auto)
  File "/opensanctions/opensanctions/core/xref.py", line 21, in blocking_xref
    xref(
  File "/usr/local/lib/python3.10/dist-packages/nomenklatura/xref.py", line 90, in xref
    _print_stats(idx, suggested, scores)
UnboundLocalError: local variable 'idx' referenced before assignment
```

**Comment by pudo** [comment]
This was an upstream bug in nomenklatura, run `pip install -U nomenklatura` to fix. It also only happens if you have no data in the database, so you may want to run `opensanctions crawl sanctions` or similar before running xref.
