### ISSUE TITLE
Cron failing sometimes

### ISSUE THREAD

**Issue by mporpaczi** [opensanctions/opensanctions#261]
Hi,

Sometimes cron fail with this message:

[2m2023-01-24 04:18:32[0m [[32m[1minfo     [0m] [1mCrawl country                 [0m [[34m[1mwd_peppercat_legislators[0m] [36mcountry[0m=[35mTuvalu[0m [36mdataset[0m=[35mwd_peppercat_legislators[0m
[2m2023-01-24 04:18:32[0m [[32m[1minfo     [0m] [1mCrawl country                 [0m [[34m[1mwd_peppercat_legislators[0m] [36mcountry[0m=[35mUganda[0m [36mdataset[0m=[35mwd_peppercat_legislators[0m
[2m2023-01-24 04:18:32[0m [[32m[1minfo     [0m] [1mCrawl country                 [0m [[34m[1mwd_peppercat_legislators[0m] [36mcountry[0m=[35mUkraine[0m [36mdataset[0m=[35mwd_peppercat_legislators[0m
[2m2023-01-24 04:18:34[0m [[32m[1minfo     [0m] [1mCrawl country                 [0m [[34m[1mwd_peppercat_legislators[0m] [36mcountry[0m=[35mUAE[0m [36mdataset[0m=[35mwd_peppercat_legislators[0m
[2m2023-01-24 04:18:34[0m [[32m[1minfo     [0m] [1mCrawl country                 [0m [[34m[1mwd_peppercat_legislators[0m] [36mcountry[0m=[35mUnited Kingdom[0m [36mdataset[0m=[35mwd_peppercat_legislators[0m
[2m2023-01-24 04:18:37[0m [[32m[1minfo     [0m] [1mCrawl country                 [0m [[34m[1mwd_peppercat_legislators[0m] [36mcountry[0m=[35mUnited States[0m [36mdataset[0m=[35mwd_peppercat_legislators[0m
[2m2023-01-24 04:19:17[0m [[32m[1minfo     [0m] [1mCrawl country                 [0m [[34m[1mwd_peppercat_legislators[0m] [36mcountry[0m=[35mUruguay[0m [36mdataset[0m=[35mwd_peppercat_legislators[0m
[2m2023-01-24 04:19:17[0m [[32m[1minfo     [0m] [1mCrawl country                 [0m [[34m[1mwd_peppercat_legislators[0m] [36mcountry[0m=[35mUzbekistan[0m [36mdataset[0m=[35mwd_peppercat_legislators[0m
[2m2023-01-24 04:19:17[0m [[32m[1minfo     [0m] [1mCrawl country                 [0m [[34m[1mwd_peppercat_legislators[0m] [36mcountry[0m=[35mVanuatu[0m [36mdataset[0m=[35mwd_peppercat_legislators[0m
[2m2023-01-24 04:19:17[0m [[32m[1minfo     [0m] [1mCrawl country                 [0m [[34m[1mwd_peppercat_legislators[0m] [36mcountry[0m=[35mVietnam[0m [36mdataset[0m=[35mwd_peppercat_legislators[0m
[2m2023-01-24 04:19:17[0m [[32m[1minfo     [0m] [1mCrawl country                 [0m [[34m[1mwd_peppercat_legislators[0m] [36mcountry[0m=[35mWales[0m [36mdataset[0m=[35mwd_peppercat_legislators[0m
[2m2023-01-24 04:19:17[0m [[32m[1minfo     [0m] [1mCrawl country                 [0m [[34m[1mwd_peppercat_legislators[0m] [36mcountry[0m=[35mZambia[0m [36mdataset[0m=[35mwd_peppercat_legislators[0m
[2m2023-01-24 04:19:17[0m [[32m[1minfo     [0m] [1mCrawl country                 [0m [[34m[1mwd_peppercat_legislators[0m] [36mcountry[0m=[35mZimbabwe[0m [36mdataset[0m=[35mwd_peppercat_legislators[0m
[2m2023-01-24 04:19:32[0m [[32m[1minfo     [0m] [1mCrawl completed               [0m [[34m[1mwd_peppercat_legislators[0m] [36mdataset[0m=[35mwd_peppercat_legislators[0m [36mentities[0m=[35m88482[0m [36mtargets[0m=[35m88482[0m
[2m2023-01-24 04:21:44[0m [[32m[1minfo     [0m] [1mCrawl completed               [0m [[34m[1mus_trade_csl[0m] [36mdataset[0m=[35mus_trade_csl[0m [36mentities[0m=[35m42696[0m [36mtargets[0m=[35m14331[0m
Traceback (most recent call last):
  File "/usr/local/bin/opensanctions", line 33, in <module>
    sys.exit(load_entry_point('opensanctions', 'console_scripts', 'opensanctions')())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1128, in __call__
{'column_67': '972-9-2357811'}
{'column_67': '972-59-2565111'}
{'column_39': "ראאד צלאח מחאג'נה - כמאל חסין חטיב - עבד אלרחים תופיק ח'ליל - "
              'יוסף עורסאן עואודה - פאדל מחמד וישאחי - חכמת פהים נעאמנה - '
              "סלימאן אחמד אגבריה - אוסאמה חסין אלעוקבי - יוסף שאהר אבו ג'אמע "
              "ונוספים ולרבות מועצת השורא (מג'לס שורא) וההנהלה הביצועית "
              "(אלאדארה אלתנפיד'יה)"}
{'column_39': 'אמין ע\'אזי אבו ראשד "אבו אברהים", שמקום מושבו בבלגיה; מחמד '
              'יוסף אל–חג\'אזי "אבו אחמד", שמקום מושבו בבלגיה; מחמד מחמוד אחמד '
              'עווד/חנון "אבו מצעב", שמקום מושבו באיטליה ; מאזן עוני עיסא כחיל '
              '"אבו אסאמה", שמקום מושבו בצרפת; מאג\'ד חליל מוסא זיר "אבו '
              'עבדאללה" שמקום מושבו בבריטניה; עאדל עבדאללה חסן דרמאן "אבו '
              'אלברא", שמקום מושבו באוסטריה;  ראמי צאלח אסמעיל עבדה "אבו '
              'צאלח", שמקום מושבו בבריטניה ;זאהר חאלד חסן ביראווי "אבו חאלד", '
              'שמקום מושבו בבריטניה; עראפת מאדי מחמוד שכרי "אבו בראא", שמקום '
              'מושבו בבריטניה; מחמד כאט\'ם רשיד מערוף צואלחה "אבו עבאדה", '
              'שמקום מושבו בבריטניה; עצאם יוסף צלאח מצטפא "אבו יוסף", שמקום '
              'מושבו בבריטניה;'}
{'column_39': 'אמין ע\'אזי אבו ראשד "אבו אברהים", שמקום מושבו בבלגיה; מחמד '
              'יוסף אל–חג\'אזי "אבו אחמד", שמקום מושבו בבלגיה; מחמד מחמוד אחמד '
              'עווד/חנון "אבו מצעב", שמקום מושבו באיטליה ; מאזן עוני עיסא כחיל '
              '"אבו אסאמה", שמקום מושבו בצרפת; מאג\'ד חליל מוסא זיר "אבו '
              'עבדאללה" שמקום מושבו בבריטניה; עאדל עבדאללה חסן דרמאן "אבו '
              'אלברא", שמקום מושבו באוסטריה;  ראמי צאלח אסמעיל עבדה "אבו '
              'צאלח", שמקום מושבו בבריטניה ;זאהר חאלד חסן ביראווי "אבו חאלד", '
              'שמקום מושבו בבריטניה; עראפת מאדי מחמוד שכרי "אבו בראא", שמקום '
              'מושבו בבריטניה; מחמד כאט\'ם רשיד מערוף צואלחה "אבו עבאדה", '
              'שמקום מושבו בבריטניה; עצאם יוסף צלאח מצטפא "אבו יוסף", שמקום '
              'מושבו בבריטניה;'}
{'column_39': 'אמין ע\'אזי אבו ראשד "אבו אברהים", שמקום מושבו בבלגיה; מחמד '
              'יוסף אל–חג\'אזי "אבו אחמד", שמקום מושבו בבלגיה; מחמד מחמוד אחמד '
              'עווד/חנון "אבו מצעב", שמקום מושבו באיטליה ; מאזן עוני עיסא כחיל '
              '"אבו אסאמה", שמקום מושבו בצרפת; מאג\'ד חליל מוסא זיר "אבו '
              'עבדאללה" שמקום מושבו בבריטניה; עאדל עבדאללה חסן דרמאן "אבו '
              'אלברא", שמקום מושבו באוסטריה;  ראמי צאלח אסמעיל עבדה "אבו '
              'צאלח", שמקום מושבו בבריטניה ;זאהר חאלד חסן ביראווי "אבו חאלד", '
              'שמקום מושבו בבריטניה; עראפת מאדי מחמוד שכרי "אבו בראא", שמקום '
              'מושבו בבריטניה; מחמד כאט\'ם רשיד מערוף צואלחה "אבו עבאדה", '
              'שמקום מושבו בבריטניה; עצאם יוסף צלאח מצטפא "אבו יוסף", שמקום '
              'מושבו בבריטניה;'}
{'column_39': 'אמין ע\'אזי אבו ראשד "אבו אברהים", שמקום מושבו בבלגיה; מחמד '
              'יוסף אל–חג\'אזי "אבו אחמד", שמקום מושבו בבלגיה; מחמד מחמוד אחמד '
              'עווד/חנון "אבו מצעב", שמקום מושבו באיטליה ; מאזן עוני עיסא כחיל '
              '"אבו אסאמה", שמקום מושבו בצרפת; מאג\'ד חליל מוסא זיר "אבו '
              'עבדאללה" שמקום מושבו בבריטניה; עאדל עבדאללה חסן דרמאן "אבו '
              'אלברא", שמקום מושבו באוסטריה;  ראמי צאלח אסמעיל עבדה "אבו '
              'צאלח", שמקום מושבו בבריטניה ;זאהר חאלד חסן ביראווי "אבו חאלד", '
              'שמקום מושבו בבריטניה; עראפת מאדי מחמוד שכרי "אבו בראא", שמקום '
              'מושבו בבריטניה; מחמד כאט\'ם רשיד מערוף צואלחה "אבו עבאדה", '
              'שמקום מושבו בבריטניה; עצאם יוסף צלאח מצטפא "אבו יוסף", שמקום '
              'מושבו בבריטניה;'}
{'column_39': 'עטאף עליאן'}
{'column_39': 'בנימין כהנא, דוד אקסלרוד ויקותיאל בן יעקב'}
{'column_39': 'ברוך מרזל, נועם פדרמן, טירן פולק'}
{'column_39': "פתחי שקאקי - עבד אלעזיז עודה - אסעד תמימי - ג'בר עמאר - אחמד "
              'מהנא - מניר שפיק - מעין טאהר'}
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opensanctions/opensanctions/cli.py", line 58, in run
    run_pipeline(dataset, threads=threads)
  File "/opensanctions/opensanctions/processing.py", line 32, in run_pipeline
    _compute_futures(futures)
  File "/opensanctions/opensanctions/processing.py", line 16, in _compute_futures
    future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opensanctions/opensanctions/core/context.py", line 242, in crawl
    self.dataset.method(self)
  File "/opensanctions/opensanctions/crawlers/everypolitician.py", line 18, in crawl
    crawl_legislature(context, code, legislature)
  File "/opensanctions/opensanctions/crawlers/everypolitician.py", line 30, in crawl_legislature
    for person in data.pop("persons", []):
AttributeError: 'NoneType' object has no attribute 'pop'

**Comment by pudo** [comment]
Try with this.

**Comment by pudo** [comment]
Closing for inactivity - probably resolved.

**Comment by mporpaczi** [comment]
Hi,

After days it was the same error:

2023-01-28 05:02:22 [info     ] Country: lu                    [everypolitician] dataset=everypolitician
/usr/local/lib/python3.10/dist-packages/structlog/dev.py:421: UserWarning: Remove `format_exc_info` from your processor chain if you want pretty exceptions.
  warnings.warn(
2023-01-28 05:02:22 [error    ] Crawl failed                   [everypolitician] dataset=everypolitician
Traceback (most recent call last):
  File "/opensanctions/opensanctions/core/context.py", line 241, in crawl
    self.dataset.method(self)
  File "/opensanctions/opensanctions/crawlers/everypolitician.py", line 16, in crawl
    crawl_legislature(context, code, legislature)
  File "/opensanctions/opensanctions/crawlers/everypolitician.py", line 28, in crawl_legislature
    for person in data.pop("persons", []):
AttributeError: 'NoneType' object has no attribute 'pop'
2023-01-28 05:02:29 [info     ] Loading ID reg documents...    [us_ofac_sdn] dataset=us_ofac_sdn
2023-01-28 05:02:40 [info     ] Crawl completed                [il_mod_terrorists] dataset=il_mod_terrorists entities=1726 targets=811
2023-01-28 05:06:54 [info     ] Crawl completed                [eu_cor_members] dataset=eu_cor_members entities=1739 targets=602
2023-01-28 05:07:05 [info     ] Crawl completed                [us_ofac_sdn] dataset=us_ofac_sdn entities=35326 targets=10228
{'column_67': '972-9-2357811'}
{'column_67': '972-59-2565111'}
{'column_39': "ראאד צלאח מחאג'נה - כמאל חסין חטיב - עבד אלרחים תופיק ח'ליל - "
              'יוסף עורסאן עואודה - פאדל מחמד וישאחי - חכמת פהים נעאמנה - '
              "סלימאן אחמד אגבריה - אוסאמה חסין אלעוקבי - יוסף שאהר אבו ג'אמע "
              "ונוספים ולרבות מועצת השורא (מג'לס שורא) וההנהלה הביצועית "
Traceback (most recent call last):
  File "/usr/local/bin/opensanctions", line 33, in <module>
    sys.exit(load_entry_point('opensanctions', 'console_scripts', 'opensanctions')())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1128, in __call__
              "(אלאדארה אלתנפיד'יה)"}
{'column_39': 'אמין ע\'אזי אבו ראשד "אבו אברהים", שמקום מושבו בבלגיה; מחמד '
              'יוסף אל–חג\'אזי "אבו אחמד", שמקום מושבו בבלגיה; מחמד מחמוד אחמד '
              'עווד/חנון "אבו מצעב", שמקום מושבו באיטליה ; מאזן עוני עיסא כחיל '
              '"אבו אסאמה", שמקום מושבו בצרפת; מאג\'ד חליל מוסא זיר "אבו '
              'עבדאללה" שמקום מושבו בבריטניה; עאדל עבדאללה חסן דרמאן "אבו '
              'אלברא", שמקום מושבו באוסטריה;  ראמי צאלח אסמעיל עבדה "אבו '
              'צאלח", שמקום מושבו בבריטניה ;זאהר חאלד חסן ביראווי "אבו חאלד", '
              'שמקום מושבו בבריטניה; עראפת מאדי מחמוד שכרי "אבו בראא", שמקום '
              'מושבו בבריטניה; מחמד כאט\'ם רשיד מערוף צואלחה "אבו עבאדה", '
              'שמקום מושבו בבריטניה; עצאם יוסף צלאח מצטפא "אבו יוסף", שמקום '
              'מושבו בבריטניה;'}
{'column_39': 'אמין ע\'אזי אבו ראשד "אבו אברהים", שמקום מושבו בבלגיה; מחמד '
              'יוסף אל–חג\'אזי "אבו אחמד", שמקום מושבו בבלגיה; מחמד מחמוד אחמד '
              'עווד/חנון "אבו מצעב", שמקום מושבו באיטליה ; מאזן עוני עיסא כחיל '
              '"אבו אסאמה", שמקום מושבו בצרפת; מאג\'ד חליל מוסא זיר "אבו '
              'עבדאללה" שמקום מושבו בבריטניה; עאדל עבדאללה חסן דרמאן "אבו '
              'אלברא", שמקום מושבו באוסטריה;  ראמי צאלח אסמעיל עבדה "אבו '
              'צאלח", שמקום מושבו בבריטניה ;זאהר חאלד חסן ביראווי "אבו חאלד", '
              'שמקום מושבו בבריטניה; עראפת מאדי מחמוד שכרי "אבו בראא", שמקום '
              'מושבו בבריטניה; מחמד כאט\'ם רשיד מערוף צואלחה "אבו עבאדה", '
              'שמקום מושבו בבריטניה; עצאם יוסף צלאח מצטפא "אבו יוסף", שמקום '
              'מושבו בבריטניה;'}
{'column_39': 'אמין ע\'אזי אבו ראשד "אבו אברהים", שמקום מושבו בבלגיה; מחמד '
              'יוסף אל–חג\'אזי "אבו אחמד", שמקום מושבו בבלגיה; מחמד מחמוד אחמד '
              'עווד/חנון "אבו מצעב", שמקום מושבו באיטליה ; מאזן עוני עיסא כחיל '
              '"אבו אסאמה", שמקום מושבו בצרפת; מאג\'ד חליל מוסא זיר "אבו '
              'עבדאללה" שמקום מושבו בבריטניה; עאדל עבדאללה חסן דרמאן "אבו '
              'אלברא", שמקום מושבו באוסטריה;  ראמי צאלח אסמעיל עבדה "אבו '
              'צאלח", שמקום מושבו בבריטניה ;זאהר חאלד חסן ביראווי "אבו חאלד", '
              'שמקום מושבו בבריטניה; עראפת מאדי מחמוד שכרי "אבו בראא", שמקום '
              'מושבו בבריטניה; מחמד כאט\'ם רשיד מערוף צואלחה "אבו עבאדה", '
              'שמקום מושבו בבריטניה; עצאם יוסף צלאח מצטפא "אבו יוסף", שמקום '
              'מושבו בבריטניה;'}
{'column_39': 'אמין ע\'אזי אבו ראשד "אבו אברהים", שמקום מושבו בבלגיה; מחמד '
              'יוסף אל–חג\'אזי "אבו אחמד", שמקום מושבו בבלגיה; מחמד מחמוד אחמד '
              'עווד/חנון "אבו מצעב", שמקום מושבו באיטליה ; מאזן עוני עיסא כחיל '
              '"אבו אסאמה", שמקום מושבו בצרפת; מאג\'ד חליל מוסא זיר "אבו '
              'עבדאללה" שמקום מושבו בבריטניה; עאדל עבדאללה חסן דרמאן "אבו '
              'אלברא", שמקום מושבו באוסטריה;  ראמי צאלח אסמעיל עבדה "אבו '
              'צאלח", שמקום מושבו בבריטניה ;זאהר חאלד חסן ביראווי "אבו חאלד", '
              'שמקום מושבו בבריטניה; עראפת מאדי מחמוד שכרי "אבו בראא", שמקום '
              'מושבו בבריטניה; מחמד כאט\'ם רשיד מערוף צואלחה "אבו עבאדה", '
              'שמקום מושבו בבריטניה; עצאם יוסף צלאח מצטפא "אבו יוסף", שמקום '
              'מושבו בבריטניה;'}
{'column_39': 'עטאף עליאן'}
{'column_39': 'בנימין כהנא, דוד אקסלרוד ויקותיאל בן יעקב'}
{'column_39': 'ברוך מרזל, נועם פדרמן, טירן פולק'}
{'column_39': "פתחי שקאקי - עבד אלעזיז עודה - אסעד תמימי - ג'בר עמאר - אחמד "
              'מהנא - מניר שפיק - מעין טאהר'}
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opensanctions/opensanctions/cli.py", line 58, in run
    run_pipeline(dataset, threads=threads)
  File "/opensanctions/opensanctions/processing.py", line 32, in run_pipeline
    _compute_futures(futures)
  File "/opensanctions/opensanctions/processing.py", line 16, in _compute_futures
    future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opensanctions/opensanctions/core/context.py", line 241, in crawl
    self.dataset.method(self)
  File "/opensanctions/opensanctions/crawlers/everypolitician.py", line 16, in crawl
    crawl_legislature(context, code, legislature)
  File "/opensanctions/opensanctions/crawlers/everypolitician.py", line 28, in crawl_legislature
    for person in data.pop("persons", []):
AttributeError: 'NoneType' object has no attribute 'pop'
