### ISSUE TITLE
Cache.clear() got an unexpected keyword argument 'conn'

### ISSUE THREAD

**Issue by jbothma** [opensanctions/opensanctions#314]
$ opensanctions clear kz_afmrk_sanctions
Traceback (most recent call last):
  File "/home/jdb/projects/opensanctions/opensanctions/env/bin/opensanctions", line 33, in <module>
    sys.exit(load_entry_point('opensanctions', 'console_scripts', 'opensanctions')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jdb/projects/opensanctions/opensanctions/env/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jdb/projects/opensanctions/opensanctions/env/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/jdb/projects/opensanctions/opensanctions/env/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jdb/projects/opensanctions/opensanctions/env/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jdb/projects/opensanctions/opensanctions/env/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jdb/projects/opensanctions/opensanctions/opensanctions/cli.py", line 84, in clear
    Context(source).clear()
  File "/home/jdb/projects/opensanctions/opensanctions/opensanctions/core/context.py", line 296, in clear
    self.cache.clear(conn=conn)
TypeError: Cache.clear() got an unexpected keyword argument 'conn'

**Comment by pudo** [comment]
Can you try `pip install -U nomenklatura`?

**Comment by jbothma** [comment]
Same result after upgrading

```
pip freeze | grep nomenklatura
nomenklatura==2.14.1
```
