### ISSUE TITLE
[li-entsg] Debared Entities should be labeled as such

### ISSUE THREAD

**Issue by brawer** [opensanctions/opensanctions#370]
On the OpenSanctions website, debarred entities get displayed with an orange label `Debarred Entity` like in [this example](https://www.opensanctions.org/entities/usgsa-s4mr1h4vg/). However, debarments per Liechtenstein Posted Workers Act currently don‘t have this label; see [example](https://www.opensanctions.org/entities/li-entsg-450328d347574d3a824f68c11527a1ac1cc49217/). Is this a UI configuration problem, or does the Liechtenstein crawler need to be changed?

**Comment by pudo** [comment]
Fair. You'd want to add `entity.add('topic', 'debarment') for each debarred entity.

**Comment by brawer** [comment]
Hm, when I change [this line](https://github.com/opensanctions/opensanctions/blob/4c08afb56dcf3fe6d40d7f95b3fa7b982f396cd2/datasets/li/posting_sanctions/crawler.py#L130) to `target.add("topic", "debarment")` with `topic`instead of the current `topics`, the following exception gets thrown:

```
2023-08-25 12:12:59 [error    ] Runner failed: Unknown property (<Schema('Company')>): topic [li_entsg] dataset=li_entsg
Traceback (most recent call last):
  File "/root/opensanctions/zavod/zavod/crawl.py", line 33, in crawl_dataset
    entry_point(context)
  File "/root/opensanctions/datasets/li/posting_sanctions/crawler.py", line 174, in crawl
    parse_debarments(context, doc)
  File "/root/opensanctions/datasets/li/posting_sanctions/crawler.py", line 130, in parse_debarments
    target.add("topic", "debarment")
  File "/usr/local/lib/python3.10/dist-packages/nomenklatura/entity.py", line 235, in add
    prop_name = self._prop_name(prop, quiet=quiet)
  File "/usr/local/lib/python3.10/dist-packages/followthemoney/proxy.py", line 120, in _prop_name
    raise InvalidData(msg % (self.schema, prop))
followthemoney.exc.InvalidData: Unknown property (<Schema('Company')>): topic
```

**Comment by pudo** [comment]
Ok so this was an interesting little bug: the debarment tag was added after the entity was emitted, which means it was never saved. I've slightly re-ordered things and let's see what happens!
