### ISSUE TITLE
Zavod not work, downloads large data, don't write to database

### ISSUE THREAD

**Issue by mporpaczi** [opensanctions/opensanctions#425]
Hi,

We updated(using the latest from repo), and using zavod now. We got these errors during crawl:

zavod crawl datasets/_collections/default.yml

2023-10-05 10:24:54 [info     ] Running dataset                [default] data_path=datasets/default data_time=2023-10-05T10:24:53 dataset=default

2023-10-05 10:24:54 [error    ] Runner failed: The dataset has no entry point! [default] dataset=default

Traceback (most recent call last):

  File "/opensanctions/zavod/zavod/crawl.py", line 32, in crawl_dataset

    entry_point = load_entry_point(dataset)

                  ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opensanctions/zavod/zavod/runtime/loader.py", line 20, in load_entry_point

    raise RuntimeError("The dataset has no entry point!")

RuntimeError: The dataset has no entry point!

2023-10-05 10:24:54 [error    ] Missing child dataset: 'ransomwhere' (in 'default') [nomenklatura.dataset.dataset]

2023-10-05 10:24:54 [error    ] Missing child dataset: 'wd_oligarchs' (in 'default') [nomenklatura.dataset.dataset]

2023-10-05 10:24:54 [error    ] Missing child dataset: 'kp_rusi_reports' (in 'default') [nomenklatura.dataset.dataset]

2023-10-05 10:24:54 [error    ] Missing child dataset: 'debarment' (in 'default') [nomenklatura.dataset.dataset]

2023-10-05 10:24:54 [error    ] Missing child dataset: 'peps' (in 'default') [nomenklatura.dataset.dataset]

2023-10-05 10:24:54 [error    ] Missing child dataset: 'ru_myrotvorets_wagner' (in 'default') [nomenklatura.dataset.dataset]

2023-10-05 10:24:54 [error    ] Missing child dataset: 'ru_billionaires_2021' (in 'default') [nomenklatura.dataset.dataset]

2023-10-05 10:24:54 [error    ] Missing child dataset: 'ru_navalny35' (in 'default') [nomenklatura.dataset.dataset]

2023-10-05 10:24:54 [error    ] Missing child dataset: 'enrichers' (in 'default') [nomenklatura.dataset.dataset]

2023-10-05 10:24:54 [error    ] Missing child dataset: 'sy_obsalytics_opensyr' (in 'default') [nomenklatura.dataset.dataset]

2023-10-05 10:24:54 [error    ] Missing child dataset: 'wd_curated' (in 'default') [nomenklatura.dataset.dataset]

2023-10-05 10:24:54 [error    ] Missing child dataset: 'md_rise_profiles' (in 'default') [nomenklatura.dataset.dataset]

2023-10-05 10:24:54 [error    ] Missing child dataset: 'sanctions' (in 'default') [nomenklatura.dataset.dataset]

2023-10-05 10:24:54 [error    ] Missing child dataset: 'wanted' (in 'default') [nomenklatura.dataset.dataset]

2023-10-05 10:24:54 [error    ] Missing child dataset: 'crime' (in 'default') [nomenklatura.dataset.dataset]

2023-10-05 10:24:54 [error    ] Missing child dataset: 'ru_acf_bribetakers' (in 'default') [nomenklatura.dataset.dataset]

2023-10-05 10:24:54 [error    ] Missing child dataset: 'ru_nsd_isin' (in 'default') [nomenklatura.dataset.dataset]

[info     ] Using cache: Engine(postgresql://opensanctions:***@*********hostname/opensanctions) [zavod.runtime.cache]

So all datasets got the same error. We using all datasets that provided. We simply use that command to crawl datasets:
zavod crawl $DATASET

We cannot understand that zavod downloaded 109GB data now, and don't written a single line to the database. Old version don't downloaded such large data, and write the results into database. How we can accomplish that in this new version? Cannot see any lines about this in the documentation. Thanks!

**Comment by pudo** [comment]
Some comments on this: 
* We've added several datasets that consume and produce really large data volumes, most notably the UK PSC database, Russian EGRUL and the GLEIF database. These are full company databases and it does not make sense to run these more often than once a month. They also don't really link into the OpenSanctions dataset (except via enrichment), so you get zero benefit out of running them, unless you have your own enrichment setup configured. 
* You cannot `crawl` collections (like `default.yml`) because they don't have crawler code linked to them. You can export and publish them, though. 
* We're no longer loading the output data to a database. That's proven to be a single point of failure in some dumb ways, so instead, the current setup just uses CSV files located in the archive folder structure. It's been much more stable and predictable as a setup.

**Comment by pudo** [comment]
Maybe aside from the technical discussion, another note: My understanding from these tickets and the discussions on Slack is that the reason you're running the OpenSanctions ETL code is to avoid having to pay the license fee required for using the data built by the OpenSanctions team. And that's totally fine - it's legally within the license rights, and it's also a cool thing to see happen. 

The only issue is with the expectation that we'll provide you support here on GitHub so that you don't have to pay us. That's a weird contradiction, and it makes it awkward for everyone.

The solution is quite simple: contribute something back! If you use OpenSanctions as an open source community member, throw some of your own contributions into the ring and make this a better thing for everyone! For example:

* You could add new data sources and crawlers, as [described here](https://zavod.opensanctions.org/tutorial/). 
* You can document your learnings and contribute to the documentation in `zavod/docs`
* You can add test cases for the data validation system 
* etc. etc. - it's really up to your creativity.
