### ISSUE TITLE
CZ Business is unhappy again

### ISSUE THREAD

**Issue by pudo** [opensanctions/opensanctions#850]
```
Traceback (most recent call last):
  File "/opensanctions/zavod/zavod/crawl.py", line 34, in crawl_dataset
    entry_point(context)
  File "/opensanctions/datasets/cz/business_register/crawler.py", line 109, in crawl
    parse_xml(context, res)
  File "/opensanctions/datasets/cz/business_register/crawler.py", line 64, in parse_xml
    tree = etree.parse(reader)
           ^^^^^^^^^^^^^^^^^^^
  File "src/lxml/etree.pyx", line 3570, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1973, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1993, in lxml.etree._parseFilelikeDocument
  File "src/lxml/parser.pxi", line 1887, in lxml.etree._parseDocFromFilelike
  File "src/lxml/parser.pxi", line 1224, in lxml.etree._BaseParser._parseDocFromFilelike
  File "src/lxml/parser.pxi", line 633, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 743, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 672, in lxml.etree._raiseParseError
  File "/opensanctions/VYSTUP/DATA/19063521.xml", line 95
lxml.etree.XMLSyntaxError: Input is not proper UTF-8, indicate encoding !
Bytes: 0x8D 0x20 0x20 0x20, line 95, column 18
```
Maybe we just catch and warn on individual XML files?

**Comment by pudo** [comment]
Skip over broken XML files: https://github.com/opensanctions/opensanctions/pull/884/commits/2c7a71d09a795a2421656925612d27608c36571f
